Still simplifying config. About to test...

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -6,6 +6,9 @@ LOG=/tmp/deploy.log
 TEST=1
 REF=
 ENV=
+REMOTEPATH=
+POSTDEPLOY=
+PROJECTNAME=
 
 #
 # Output usage information.
@@ -102,7 +105,7 @@ version() {
 #
 
 run() {
-  local url="`config_get user`@`config_get host`"
+  local url="$PROJECTNAME@`config_get host`"
   local key=`config_get key`
   if test -n "$key"; then
     local shell="ssh -i $key $url"
@@ -118,7 +121,7 @@ run() {
 #
 
 console() {
-  local url="`config_get user`@`config_get host`"
+  local url="$PROJECTNAME@`config_get host`"
   local key=`config_get key`
   if test -n "$key"; then
     local shell="ssh -i $key $url"
@@ -146,19 +149,16 @@ config() {
 #
 
 hook() {
-  test -n "$1" || abort hook name required
-  local hook=$1
-  local path=`config_get path`
-  local cmd=`config_get $hook`
+  local path=$REMOTEPATH
+  local cmd=$1
+  test -n "$cmd" || abort hook name required
   if test -n "$cmd"; then
-    log "executing $hook \`$cmd\`"
+    log "executing \`$cmd\`"
     run "cd $path/current; \
       SHARED=\"$path/shared\" \
       $cmd 2>&1 | tee -a $LOG; \
       exit \${PIPESTATUS[0]}"
     test $? -eq 0
-  else
-    log hook $hook
   fi
 }
 
@@ -167,7 +167,7 @@ hook() {
 #
 
 setup() {
-  local path=`config_get path`
+  local path=$REMOTEPATH
   local repo=`config_get repo`
   run "mkdir -p $path/{shared/{logs,pids},source}"
   test $? -eq 0 || abort setup paths failed
@@ -184,10 +184,10 @@ setup() {
 
 deploy() {
   local ref=$1
-  local path=`config_get path`
+  local path=$REMOTEPATH
   log deploying
 
-  hook pre-deploy || abort pre-deploy hook failed
+  #hook pre-deploy || abort pre-deploy hook failed
 
   # fetch source
   log fetching updates
@@ -219,7 +219,7 @@ deploy() {
       >> $path/.deploys"
   test $? -eq 0 || abort deploy log append failed
 
-  hook post-deploy || abort post-deploy hook failed
+  hook "$POSTDEPLOY" || abort post-deploy hook failed
 
   if test $TEST -eq 1; then
     hook test
@@ -240,7 +240,7 @@ deploy() {
 #
 
 current_commit() {
-  local path=`config_get path`
+  local path=$REMOTEPATH
   run "cd $path/source && \
       git rev-parse --short HEAD"
 }
@@ -251,7 +251,7 @@ current_commit() {
 
 nth_deploy_commit() {
   local n=$1
-  local path=`config_get path`
+  local path=$REMOTEPATH
   run "cat $path/.deploys | tail -n $n | head -n 1 | cut -d ' ' -f 1"
 }
 
@@ -260,7 +260,7 @@ nth_deploy_commit() {
 #
 
 list_deploys() {
-  local path=`config_get path`
+  local path=$REMOTEPATH
   run "cat $path/.deploys"
 }
 
@@ -293,6 +293,12 @@ revert_to() {
 require_env() {
   config_section $ENV || abort "[$ENV] config section not defined"
   test -z "$ENV" && abort "<env> required"
+
+  # settings that can be computed from the deploy.conf vars
+  PROJECTNAME=`config_get project`
+  test -z "$PROJECTNAME" && abort "project name must be specified in deploy.conf"
+  REMOTEPATH="/home/$PROJECTNAME/app"
+  POSTDEPLOY="post-deploy npm install && [ -e /var/run/$PROJECTNAME.pid ] && sudo restart $PROJECTNAME || sudo start $PROJECTNAME"
 }
 
 #
@@ -321,7 +327,7 @@ while test $# -ne 0; do
     -c|--config) set_config_path $1; shift ;;
     -C|--chdir) log cd $1; cd $1; shift ;;
     -T|--no-tests) TEST=0 ;;
-    run|exec) require_env; run "cd `config_get path` && $@"; exit ;;
+    run|exec) require_env; run "cd $REMOTEPATH && $@"; exit ;;
     console) require_env; console; exit ;;
     curr|current) require_env; current_commit; exit ;;
     prev|previous) require_env; nth_deploy_commit 2; exit ;;
